# Generated by Django 6.0.2 on 2026-02-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_description_alter_product_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(db_comment='Precio unitario final', decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
    ]
