# Generated by Django 6.0.2 on 2026-02-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_product_price_product_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='Timestamp de creación del registro'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, db_comment='Descripción extendida del producto', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_comment='Control lógico de disponibilidad', default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_comment='Nombre comercial del producto', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_comment='Identificador estable usado entre sistemas', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(db_comment='Precio unitario con precisión decimal', decimal_places=2, max_digits=12),
        ),
    ]
